# Client Service Configuration
spring:
  application:
    name: client-service
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: ${DB_USERNAME:client_user}
    password: ${DB_PASSWORD:client_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server configuration
server:
  port: 8081

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.cs301: DEBUG
    org.springframework: INFO
    org.hibernate: WARN