{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-sidecar
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
    component: sidecar
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
{{- end }}