name: Run Tests

on:
  push: # Run tests on every push to any branch
    branches:
      - '**'
  pull_request: # Also run tests on any PR to any branch
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Protobuf Classes
        run: ./gradlew generateProto

      - name: Run Tests
        run: ./gradlew test --no-daemon
        env:
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILE }}
