---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-prod
spec:
  acme:
    email: yaxit77590@birige.com # temp mail
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-prod-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
