# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-metrics
#   namespace: ingress
#   labels:
#     app: nginx-ingress-metrics
# spec:
#   ports:
#     - name: prometheus
#       protocol: TCP
#       port: 10254
#       targetPort: 10254
#   selector:
#     app: nginx-ingress-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor
  namespace: ingress
  labels:
    release: prometheus-k8s
spec:
  selector:
    matchLabels:
      app: nginx-ingress-metrics
  endpoints:
    - port: prometheus
      path: /metrics