---
# App of Apps (Scrooge Bank master app)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrooge-bank-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cs301-crm/project-2024-25t2-301-g3t3-charts
    targetRevision: HEAD
    path: environments/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
